<a href="https://colab.research.google.com/github/Darshan235/ML/blob/main/Lab_8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# SVR on Insurance Dataset
This notebook trains SVR models with different kernels to predict insurance cost.

In [1]:

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.svm import SVR
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [2]:

# Load dataset
df = pd.read_csv("insurance.csv")
df.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [3]:

# Encode categorical variables
label_encoders = {}
for col in ['sex', 'smoker', 'region']:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col])
    label_encoders[col] = le

df.head()

   age  sex     bmi  children  smoker  region      charges
0   19    0  27.900         0       1       3  16884.92400
1   18    1  33.770         1       0       2   1725.55230
2   28    1  33.000         3       0       2   4449.46200
3   33    1  22.705         0       0       1  21984.47061
4   32    1  28.880         0       0       1   3866.85520

In [4]:

# Feature selection
X = df.drop('charges', axis=1)
y = df['charges']

In [5]:

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [6]:

# Feature scaling
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [7]:

def evaluate_model(model, X_test, y_test):
    y_pred = model.predict(X_test)
    mae = mean_absolute_error(y_test, y_pred)
    rmse = np.sqrt(mean_squared_error(y_test, y_pred))
    r2 = r2_score(y_test, y_pred)
    return mae, rmse, r2

In [8]:

# SVR with RBF kernel
svr_rbf = SVR(kernel='rbf')
svr_rbf.fit(X_train, y_train)

rbf_results = evaluate_model(svr_rbf, X_test, y_test)
rbf_results

(8599.328962388287, np.float64(12877.868997800848), -0.06821813183902203)

In [9]:

# SVR with Polynomial kernel
svr_poly = SVR(kernel='poly', degree=3)
svr_poly.fit(X_train, y_train)

poly_results = evaluate_model(svr_poly, X_test, y_test)
poly_results

(8589.57234098436, np.float64(12847.736896823724), -0.06322506975686526)

In [10]:

# Comparison
results = pd.DataFrame({
    'Kernel': ['RBF', 'Polynomial'],
    'MAE': [rbf_results[0], poly_results[0]],
    'RMSE': [rbf_results[1], poly_results[1]],
    'R2 Score': [rbf_results[2], poly_results[2]]
})

results

       Kernel          MAE          RMSE  R2 Score
0         RBF  8599.328962  12877.868998 -0.068218
1  Polynomial  8589.572341  12847.736897 -0.063225


## Conclusion
The kernel with **lower MAE & RMSE** and **higher R² score** performs better for predicting insurance cost.